# Bonusmaterial: Matrix-Multiplikation

(c) 2023 by Harald Bögeholz

---

In [2]:
import numpy as np

In [3]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
B=np.array([[1,2],[0,1],[-1,0]])
B

array([[ 1,  2],
       [ 0,  1],
       [-1,  0]])

Matrix-Multiplikation schreibt man in Numpy mit `@`

In [5]:
A @ B

array([[-2,  4],
       [-2, 13]])

In [6]:
Z=np.array([[1,2,3]])
Z

array([[1, 2, 3]])

In [7]:
S=np.array([[4],[5],[6]])
S

array([[4],
       [5],
       [6]])

Zeilenvektor multipliziert mit Spaltenvektor ergibt nur eine einzige Zahl:

In [8]:
Z @ S

array([[32]])

Spaltenvektor mal Zeilenvektor ergibt in diesem Fall eine 3x3-Matrix (3x1- mal 1x3-Matrix)

In [9]:
X = S @ Z
X

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

Es kommt bei der Matrix-Multiplikation also auf die Reihenfolge an! `A @ B` ist nicht gleich `B @ A`!

In [10]:
Y = np.array([[1,0,1],[2,-2,3],[0,1,2]])
Y

array([[ 1,  0,  1],
       [ 2, -2,  3],
       [ 0,  1,  2]])

In [11]:
X @ Y

array([[20, -4, 52],
       [25, -5, 65],
       [30, -6, 78]])

**Achtung:** Normale Multiplikation mit `*` arbeitet komponentenweise. Das ist *nicht* die Matrix-Multiplikation

In [12]:
X * Y

array([[  4,   0,  12],
       [ 10, -20,  45],
       [  0,  12,  36]])

So findet man die Dimensionen einer Matrix heraus:

In [13]:
A.shape

(2, 3)

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6]])

Mit der Funktion `reshape()` bringt man Arrays in eine andere Form. Das klappt aber nur, wenn die gewünschten Dimensionen zur Anzahl der Elemente passen.

In [14]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
A.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [17]:
C = np.array(range(1, 13))
C

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
C.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
C.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
C.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [21]:
C.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [22]:
C.reshape(7,3)

ValueError: cannot reshape array of size 12 into shape (7,3)